import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion"

const faqs = [
  {
    question: "What is Nano Banana?",
    answer:
      "Nano Banana is a web app for AI-assisted image editing. You upload an image, describe your desired change, and the app returns edited outputs generated by third-party AI models.",
  },
  {
    question: "How does it work?",
    answer:
      "Your image(s) and prompt are sent to an AI provider for processing, then the results are returned to your browser. Output quality can vary by image and prompt.",
  },
  {
    question: "Who provides the AI model?",
    answer:
      "Nano Banana is an interface and does not host its own model. It routes requests to third-party providers (via an AI routing service) and returns the generated images.",
  },
  {
    question: "Can I use it for commercial projects?",
    answer:
      "You are responsible for ensuring you have the rights to use your inputs and publish the outputs. Review the provider terms and our Terms of Service for details.",
  },
  {
    question: "What types of edits can it handle?",
    answer:
      "Common edits include background changes, object placement/removal, style changes, and variations based on your prompt. Results are not guaranteed and may require iteration.",
  },
  {
    question: "Where can I try Nano Banana?",
    answer:
      "Use the editor on this site: upload an image, enter a prompt, and generate results. If you have questions, see the Contact page.",
  },
]

export function FAQ() {
  return (
    <section id="faq" className="bg-muted/30 py-20">
      <div className="container mx-auto px-4">
        <div className="mb-12 text-center">
          <h2 className="mb-2 text-sm font-semibold uppercase tracking-wider text-banana-600">FAQs</h2>
          <h3 className="text-3xl font-bold text-foreground md:text-4xl">Frequently Asked Questions</h3>
        </div>

        <div className="mx-auto max-w-3xl">
          <Accordion type="single" collapsible className="w-full">
            {faqs.map((faq, index) => (
              <AccordionItem key={index} value={`item-${index}`} className="border-banana-200/50">
                <AccordionTrigger className="text-left text-foreground hover:text-banana-600">
                  {faq.question}
                </AccordionTrigger>
                <AccordionContent className="text-muted-foreground">{faq.answer}</AccordionContent>
              </AccordionItem>
            ))}
          </Accordion>
        </div>
      </div>
    </section>
  )
}
